web_root: "/var/www"
domain_name: ansible2.codecodac.com
vm_ip: 98.67.160.132
vm_user: "ubuntu"
vm_password: "CerbuTechUbuntu!"
domain_title: Ansible Demo
wp_version: 6.3.1
certbot_admin_email: noreply@cerbu.tech
php_version: 8.1
ssh_key_path: "/var/ansible/keys/git_key.pub"
wordpress_plugins_path: "/var/www/{{ domain_name }}/wp-content/plugins"
wp_email: mariutamihaidan@gmail.com
wp_user: administrator
wp_password: CerbuTechUbuntu!

# Customer data
customer_name: "Shop la cheie SRL"
customer_city: "Craiova"
customer_zip: "617410000"
customer_cui: "12345677899"
customer_j: "J23/23/1999"
customer_support_email: "support@mysite.ro"
customer_support_phone: "0745123456"
customer_support_address: "Strada Mihai Viteazul, Numărul 37, Cârcea, Dolj"
customer_bank: "Banca Transilvania"
customer_iban: "IBAN123456"

# Defaults
replace_content: true  #uneused yet

# DB
db_name: wordpress
db_user: shop
db_password: CerbuTechUbuntu!
db_host: ansible-mysql.mysql.database.azure.com

# Smartbill
smartbill_options:
  username: 111111111
  password: 22222222
  vat_code: 3333333333
  token: 44444444444444
  smartbill_password: smartbill_secured_password

# Github updater
github_updater_token: 5ba9d4b3833ccf3d2b106f6fef31e385ec201576
github_updater_api_key: 7770243b2ace4c927094e7ff1be31e0c

# WP_CONFIG.PHP
wp_debug: false
wp_debug_display: false
wp_debug_log: false

# NOD CONNECTOR API credentials
nod_api_url: http://api.b2b-sbx.nod.ro
nod_api_user: 57d620670fed93307cc3cde577f18162
nod_api_key: 8f3d70f0b7e1e81198b21775083b87d1

# Azure cloud storage
azure_storage_use_for_default_upload: 1
microsoft_azure_account_name: nodcdn
microsoft_azure_account_key: MepgF3FaTJU8NxKuatMpZdx+N2DXkfCi6SIU8W+tA19cGvPa3BqA6Y6ibn1rFmnPQJHYmrWezWwjr3bSvCjEoQ==
microsoft_azure_container: octombrie
azure_storage_account_name: r156
azure_storage_account_primary_access_key: tjtW/F99XPPKB0D6I1UsygOrYORF/qcWZz+0obf9CFzSJT+rSwx44kkQ+PGc6iYie/UE+LnS5fVL+AStYh/knA==
default_azure_storage_account_container_name: saas
azure_browse_cache_results: 15
azure_cache_control: 600

# Electro options
electro_options:
  redux-section: "11"
  last_tab: "8"
  dark_enabled: 0
  mode_switcher_enabled: 0
  scrollup: "1"
  reg_image_size: "0"
  sidebar_margin_top: "268"
  load_child_theme: "0"
  catalog_mode: "0"
  compare_page_id: ""
  product_archive_enabled_views:
    enabled:
      placebo: "placebo"
      grid: "Grid"
      grid-extended: "Grid Extended"
      list-view: "List"
      list-view-small: "List View Small"
    disabled:
      placebo: "placebo"
  shop_layout: "left-sidebar"
  subcategory_columns: "3"
  product_columns: "3"
  product_columns_wide: "5"
  products_per_page: "15"
  wc_template_loop_sale: "0"
  single_product_layout: "left-sidebar"
  single_product_style: "normal"
  enable_single_product_sidebar: "0"
  enable_related_products: "1"
  single_product_timer: "0"
  product_gallery_carousel: "0"
  sticky_add_to_cart_mobile: "0"
  myaccount_before_login_text: ""
  myaccount_before_register_text: ""
  myaccount_register_benefits_title: "Sign up today and you will be able to :"
  myaccount_register_benefits:
    - "Speed your way through checkout"
    - "Track your orders easily"
    - "Keep a record of all your purchases"
  dokan_store_list_version: ""
  dokan_store_list_sidebar: "1"
  dokan_electro_store_style: "0"
  dokan_store_version: "store-v1"
  dokan_store_sidebar: "0"
  dokan_store_owner_info: "1"
  header_top_bar_show: "1"
  header_top_bar_show_mobile: "0"
  header_enable_topbar_additional_links: 1
  header_topbar_additional_links_title: "Two Shops<br>One Shipment"
  header_topbar_additional_link_1_text: "Electronics"
  header_topbar_additional_link_1_url: "#"
  header_topbar_additional_link_1_image:
    url: ""
    id: ""
    height: ""
    width: ""
    thumbnail: ""
  header_topbar_additional_link_2_text: "Power Tools"
  header_topbar_additional_link_2_url: "#"
  header_topbar_additional_link_2_image:
    url: ""
    id: ""
    height: ""
    width: ""
    thumbnail: ""
  header_show_tooltip: "1"
  header_icon_tooltip_position: "bottom"
  header_style: "v2"
  sticky_header: "0"
  site_header_logo:
    url: ""
    id: ""
    height: ""
    width: ""
    thumbnail: ""
  off_canvas_nav_in_desktop: "1"
  header_vertical_menu_title: "Categorii Produse"
  header_vertical_menu_icon: "fa fa-list-ul"
  header_departments_menu_title: "Shop By Department"
  header_v5_departments_menu_title: "Categorii Produse"
  header_v6_departments_menu_title: "Categorii"
  header_navbar_search_placeholder: "Cautati produse"
  enable_header_navbar_search_dropdown: "1"
  header_navbar_search_dropdown_categories: "show_only_top_level"
  header_navbar_search_dropdown_text: "Toate categoriile"
  header_live_search: "1"
  header_support_block_show: "1"
  header_support_number: "<strong>Suport</strong> {{customer_support_phone}}"
  header_support_email: "Email: {{customer_support_email}}"
  header_cart_icon: "ec ec-shopping-bag"
  header_cart_dropdown_disable: "0"
  off_canvas_cart: "0"
  header_user_account_enable: "0"
  header_user_account_icon: "ec ec-user"
  header_user_account_logged_in_menu: "0"
  show_footer_brands_slider: "0"
  footer_enable_touch_slider: "0"
  footer_footer_brands_slider_number: "12"
  show_footer_widgets: "1"
  footer_widgets_columns: "4"
  show_footer_newsletter: "0"
  footer_newsletter_title: "Sign up to Newsletter"
  footer_newsletter_marketing_text: "...and receive <strong>$20 coupon for first shopping</strong>"
  footer_newsletter_signup_form: ""
  show_footer_contact_block: "1"
  show_footer_logo: "0"
  site_footer_logo:
    url: ""
    id: ""
    height: ""
    width: ""
    thumbnail: ""
  show_footer_call_us: "1"
  footer_call_us_text: "Telefon"
  footer_call_us_icon: "ec ec-support"
  footer_call_us_number: "{{customer_support_phone}}"
  show_footer_address: "1"
  footer_address_title: "Adresă"
  footer_address: "{{customer_support_address}}"
  show_footer_social_icons: "0"
  show_footer_bottom_widgets: "1"
  footer_bottom_widgets_columns: "3"
  footer_credit_block_enable: "1"
  footer_credit: "&copy; <a href=\"https://{{domain_name}}/\">WordPress</a> - All Rights Reserved"
  footer_credit_icons: ""
  enable_mobile_frontpage: "0"
  mobile_frontpage_id: ""
  handheld_header_logo:
    url: ""
    id: ""
    height: ""
    width: ""
    thumbnail: ""
  handheld_header_style: "handheld-v2"
  handheld_header_v2_light_bg: "0"
  sticky_handheld_header: "0"
  enable_add_to_cart_mobile: "0"
  handheld_footer_bar_home_icon: "si si-home"
  handheld_footer_bar_cart_icon: "ec ec-shopping-bag"
  handheld_footer_bar_user_icon: "si si-user"

public_plugins:
  - name: advanced-cron-manager
    version: 2.5.2
    activate: true
  - name: one-click-demo-import
    version: 3.1.2
    activate: false
  - name: mainwp-child
    version: 4.5.2
    activate: false
  - name: windows-azure-storage
    version: 4.4.0
    activate: false
  - name: redux-framework
    version: 4.4.9
    activate: true
  - name: autoptimize
    version: 3.1.9
    activate: false
  - name: mas-woocommerce-brands
    version: 1.0.7
    activate: true
  - name: mas-static-content
    version: 1.0.5
    activate: false
  - name: one-click-demo-import
    version: 3.1.2
    activate: false
  - name: wordpress-importer
    version: 0.8.1
    activate: false
  - name: advanced-nocaptcha-recaptcha
    version: 7.3.1
    activate: false
  - name: netopia-payments-payment-gateway
    version: 1.3
    activate: false
  - name: wpforms-lite
    version: 1.8.4
    activate: true
  - name: yith-woocommerce-compare
    version: 2.32.0
    activate: false
  - name: yith-woocommerce-wishlist
    version: 3.26.0
    activate: false
  - name: premmerce-woocommerce-product-filter
    version: 3.7.2
    activate: true
  - name: regenerate-thumbnails
    version: 3.1.6
    activate: false
  - name: user-role-editor
    version: 4.64.1
    activate: false
plugins:
  - name: github-updater
    repo: "git@github.com:afragen/git-updater.git"
    version: 8.7.0
    activate: false
  - name: nod-wordpress-module
    repo: "git@github.com:nod-ro/nod-wordpress-module.git"
    version: 1.5.7
    activate: true
  - name: nod-wordpress-marketplace-emag
    repo: "git@github.com:nod-ro/nod-wordpress-marketplace-emag.git"
    version: release-2.0.4
    activate: false
  - name: nod-connector-b2b
    repo: "git@github.com:nod-ro/nod-connector-b2b.git"
    version: 1.0.4
    activate: false
  - name: nod-shop-saas
    repo: "git@github.com:nod-ro/nod-shop-saas.git"
    version: 1.0.7
    activate: true
  - name: nod-smartbill
    repo: "git@github.com:nod-ro/nod-smartbill.git"
    version: 2.2.6.2-shops
    activate: true
external_plugins:
  - name: "Electro Extensions"
    slug: "electro-extensions"
    url: "https://transvelo.github.io/electro/assets/plugins/electro-extensions.zip"
    version: "3.3.13"
  - name: "Envato Market"
    slug: "envato-market"
    url: "https://envato.github.io/wp-envato-market/dist/envato-market.zip"
    version: "2.0.6"
  - name: "Revolution Slider"
    slug: "revolution-slider"
    url: "https://transvelo.github.io/included-plugins/revslider.zip"
    version: "6.3.3"
  - name: "WPBakery Page Builder"
    slug: "wpbakery-page-builder"
    url: "https://transvelo.github.io/included-plugins/js_composer.zip"
    version: "6.5.0"
themes:
  - name: nod-electro-theme
    repo: "git@github.com:nod-ro/nod-electro-theme.git"
    version: 3.0.1
  - name: nod-electro-theme-child
    repo: "git@github.com:nod-ro/nod-electro-theme-child.git"
    version: release-1.0.7
pages:
  - slug: home
    title: Prima pagina
  - slug: contact
    title: Contact
  - slug: termeni-si-conditii
    title: Termeni si conditii
  - slug: retur
    title: Retur
  - slug: livrare
    title: Livrare

menu_top_bar_right_slugs:
  - my-account
  - retur
  - livrare
  - contact
  - termeni-si-conditii